on:
  push:

jobs:

  spring:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.7
      - run: java -version
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java -version
      - run: |
          chmod +x gradlew 
          ./gradlew bootjar

      - run: docker build .

      - run: docker images