on:
  push:

jobs:

  spring:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.7

      - run: |
          chmod +x gradlew 
          ./gradlew bootjar

      - run: docker build .

      - run: docker images