on:
  push:

permissions:
  packages: write

jobs:

  spring:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.7
      - run: java -version
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java -version
      - run: |
          chmod +x gradlew 
          ./gradlew bootjar

      - run: |
          docker build -t spring-java17:latest .
          docker tag spring-java17:latest ghcr.io/${{ github.repository }}/spring-java17:latest

      - env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin

      - run: docker images

      - run: docker push ghcr.io/${{ github.repository }}/spring-java17:latest

